 <!--
  - @copyright Copyright (c) 2021 John Molakvoæ <skjnldsv@protonmail.com>
  -
  - @author John Molakvoæ <skjnldsv@protonmail.com>
  -
  - @license GNU AGPL version 3 or any later version
  -
  - This program is free software: you can redistribute it and/or modify
  - it under the terms of the GNU Affero General Public License as
  - published by the Free Software Foundation, either version 3 of the
  - License, or (at your option) any later version.
  -
  - This program is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  - GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License
  - along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -
  -->
<template>
	<Content app-name="unsupported-browser" class="content-unsupported-browser">
		<EmptyContent>
			{{ t('core', 'This browser is not supported') }}
			<template #icon>
				<Web />
			</template>
			<template #desc>
				<div>
					{{ t('core', 'Please upgrade to a more recent browser') }}
					<button class="content-unsupported-browser__continue" @click="forceBrowsing">
						{{ t('core', 'Continue with this outdated browser') }}
					</button>
				</div>

				<ul class="content-unsupported-browser__list">
					<h3>{{ t('core', 'Supported versions') }}</h3>
					<li v-for="browser in formattedBrowsersList" :key="browser">
						{{ browser }}
					</li>
				</ul>
			</template>
		</EmptyContent>
	</Content>
</template>

<script>
import { generateUrl } from '@nextcloud/router'
import { translate as t, translatePlural as n } from '@nextcloud/l10n'
import Content from '@nextcloud/vue/dist/Components/Content'
import EmptyContent from '@nextcloud/vue/dist/Components/EmptyContent'
import Web from 'vue-material-design-icons/Web'

// eslint-disable-next-line node/no-extraneous-import
import { agents } from 'caniuse-lite'

import browserStorage from '../services/BrowserStorageService'
import { supportedBrowsers } from '../services/BrowsersListService'
import { browserStorageKey } from '../utils/RedirectUnsupportedBrowsers'
import logger from '../services/LoggerService'

logger.debug('Supported browsers', { supportedBrowsers })

export default {
	name: 'UnsupportedBrowser',
	components: {
		Web,
		Content,
		EmptyContent,
	},

	computed: {
		formattedBrowsersList() {
			const list = {}

			// supportedBrowsers is generated by webpack at compilation time
			supportedBrowsers.forEach(browser => {
				const [id, version] = browser.split(' ')
				if (!list[id] || list[id] < parseFloat(version, 10)) {
					list[id] = parseFloat(version, 10)
				}
			})

			return Object.keys(list).map(id => {
				const version = list[id]
				const name = agents[id].browser
				return this.t('core', '{name} version {version} and above', {
					name, version,
				})
			})
		},
	},

	methods: {
		t,
		n,

		// Set the flag allowing this browser and redirect to home
		forceBrowsing() {
			browserStorage.setItem(browserStorageKey, true)
			window.location = generateUrl('/')
		},
	},
}
</script>

<style lang="scss" scoped>
.content-unsupported-browser {
	display: flex;
	justify-content: center;
	width: 500px;
	max-width: 90vw;
	margin: auto;
	padding: 30px;
	cursor: default;
	color: #fff;
	border-radius: 10px;
	background-color: rgba(0,0,0,.3);

	.empty-content {
		margin: 0;
		&::v-deep .empty-content__icon {
			opacity: 1;
		}
	}

	&__continue {
		display: block;
		margin: 20px auto;
	}

	&__list {
		margin-top: 60px;
		margin-bottom: 40px;
		li {
			text-align: left;
		}
	}
}

</style>
