codecov:
  branch: master
  ci:
    - drone.nextcloud.com
    - !scrutinizer-ci.com

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
