kind: pipeline
name: integration-federation_features

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: integration-federation_features
  image: nextcloudci/php7.4:php7.4-3
  commands:
    - composer global require hirak/prestissimo
    - bash tests/drone-run-integration-tests.sh || exit 0
    - ./occ maintenance:install --admin-pass=admin
    - cd build/integration
    - ./run.sh federation_features/federated.feature

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
