name: "Unit tests"

on:
  push:
  pull_request:

jobs:
  phpunit-oci8:
    name: "PHPUnit on OCI8"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

    services:
      oracle:
        image: deepdiver/docker-oracle-xe-11g # "wnameless/oracle-xe-11g-r2"
        ports:
          - "1521:1521"


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, oci8
          tools: phpunit:8.5.2
          coverage: none

            #- name: Run tests
            #run: NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php status.php

      - name: Run phpunit
        run: |
          cd tests && phpunit --configuration phpunit-autotest.xml --group DB,SLOWDB

        #- name: Run tests
        #  run: NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh oci
